export const ActionTypes = {
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  SET_PRODUCTS: "SET_PRODUCTS",
  GET_PRODUCTS:"GET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
